bwm-ng: add package (ver 0.6.3)
omniosorg/omnios-extra pull request #1072
Opened 2022-03-08 04:40 UTC by bahamas10

a fairly straight forward package add, i've been using `bwm-ng` for about 15 years and it's pretty much muscle-memory for me at this point.  source https://github.com/vgropp/bwm-ng

Concerns
----------

I chose what i thought was the best name for this (`ooce/network/bwm-ng`) but if it better fits under another category i'm fine with changing it.

Testing
-------

```
$ sudo pkg install bwm-ng
$ bwm-ng -h
Bandwidth Monitor NG (bwm-ng) v0.6.3USAGE: bwm-ng [OPTION] ... [CONFIGFILE]
displays current ethernet interfaces stats
...
```

2022-03-08 07:49 UTC, oetiker approved these changes

2022-03-08 10:25 UTC, citrus-it requested changes
Looks good, thanks!

2022-03-08 10:25 UTC, citrus-it commented on build/bwm-ng/build.sh
> +download_source v$VER $PROG $VER
I've put this onto the mirror now.

```suggestion

init
download_source $PROG v$VER
```

2022-03-08 10:25 UTC, citrus-it commented on build/bwm-ng/build.sh
> +prep_build
Please add the `patch_source` line above this one
(even though there are no patches, this is used for some hooks so all packages should have it)

2022-03-08 11:09 UTC, citrus-it commented on build/bwm-ng/build.sh
> +PKG=ooce/network/$PROG
Unfortunately, this line cannot use variables
```suggestion
PKG=ooce/network/bwm-ng
```

2022-03-08 18:24 UTC, bahamas10 commented
> Looks good, thanks!

Thank you for the review! I've pushed a new commit with all of the changes you've outlined.

2022-03-09 00:43 UTC, citrus-it approved these changes

2022-03-09 10:22 UTC, merged