tig: add package (ver 2.5.5)
omniosorg/omnios-extra pull request #1135
Opened 2022-07-08 08:22 UTC by nospam3089

Running `build.sh` results in an `--- Comparing old package with new` error. Maybe I've done some mistake with adding to `doc/baseline`? I attempted to follow the instructions and mimicked earlier commits in the history (such as e.g. 1e8d76da).

There are also a bunch of these warnings when building on an up-to-date bloody:

>   .../omnios-extra/lib/functions.sh: line 193: /opt/onbld/bin/find_elf: No such file or directory

I'm posting as a draft PR for now. If anyone would be able to provide some insight in what I've missed, that would be most appreciated.

2022-07-08 09:41 UTC, citrus-it commented
Thanks for the contribution.

> Running `build.sh` results in an `--- Comparing old package with new` error

This is probably just telling you that it's found a difference between the previous version of the package and the new one. Since the package is new and there is no previous version, all of the files are reported as additions. You can just answer `yes` after reviewing the files that are being delivered and the error will not show up once there is a published version of this package.

> .../omnios-extra/lib/functions.sh: line 193: /opt/onbld/bin/find_elf: No such file or directory

This is a known issue in bloody (fixed by https://github.com/omniosorg/illumos-omnios/pull/1191 ) and the next bloody update will include that fix. In the meantime you could add a manual symlink with something like:

```
% pfexec ln -s i386/find_elf /opt/onbld/bin/find_elf
```

2022-07-08 10:15 UTC, nospam3089 commented
Excellent! Thank you @citrus-it. I'll just switch this from a draft to a proper pull request then.

2022-07-08 16:00 UTC, hadfl requested changes
Thank you for your contribution, this looks really good. Just a few nits.

2022-07-08 17:57 UTC, nospam3089 commented on doc/packages.md
> +| ooce/application/tig 		| 2.5.5		| Rhttps://github.com/jonas/tig/releases | [omniosorg](https://github.com/omniosorg)
Woops, how embarrassing! Apologies for that. Guess the network lag on the tram was worse than I realized when I messed that one up. The three issues should be fixed in updated commit. Thanks for catching my errors!

2022-07-11 08:14 UTC, oetiker approved these changes

2022-07-11 16:42 UTC, hadfl requested changes
Thank you for the cleanup and sorry for the delay, I finally had time to have a closer look and do a test build. There are two things I'd like you to have a look:
- `tig` ships a `tigrc` config file, which lands directly under `/etc/opt/ooce`; we usually try to avoid that but rather use a program specific `PREFIX`
- `tig` does not install the man page with the default `install` target. `install-doc-man` should be added to `MAKE_INSTALL_TARGET`

Please have a look at the following commit and and adjust your PR if it makes sense to you:
https://github.com/hadfl/omnios-extra/commit/361ec5375923ef7e932caff0fb5625d6857858ea

2022-07-13 15:10 UTC, hadfl approved these changes
Thank you for your feedback regarding the changes.

I've squashed them on top of your commit (keeping you as the author).

2022-07-13 15:27 UTC, citrus-it approved these changes

2022-07-13 15:28 UTC, merged