tailscale: update to 1.38.1
omniosorg/omnios-extra pull request #1259
Opened 2023-03-16 14:14 UTC by nshalman

2023-03-16 22:04 UTC, citrus-it requested changes

2023-03-17 00:15 UTC, nshalman commented on build/tailscale/build.sh
> +set_gover 120
Fixed.

2023-03-17 06:34 UTC, hadfl approved these changes

2023-03-17 09:01 UTC, oetiker approved these changes

2023-03-17 13:38 UTC, citrus-it approved these changes

2023-03-17 13:39 UTC, merged