Update atuin to v17.0.0
omniosorg/omnios-extra pull request #1361
Opened 2023-10-26 17:40 UTC by papertigers

Version 17.0.0 just released: https://github.com/atuinsh/atuin/releases/tag/v17.0.0

I haven't run through a build of this, but I am filing the PR anyways.

2023-10-29 10:24 UTC, oetiker submitted a review, later dismissed

2023-10-29 11:52 UTC, hadfl requested changes

2023-10-29 11:52 UTC, hadfl commented on build/atuin/build.sh
> +VER=17.0.0
In the meantime version `17.0.1` has been released. Would you mind bumping it to the latest release?

2023-10-29 11:55 UTC, hadfl requested changes
Also the build seems to fail, we'd appreciate if you could have a look and fix it if possible. Thanks

2024-01-04 12:08 UTC, oetiker commented
any progress ?

2024-02-06 22:15 UTC, papertigers commented
Sorry haven't had time to put together the necessary patch on the atuin side.  
Let me see if I can make some time soon to push that along.

2024-03-13 15:30 UTC, citrus-it commented
18.1.0 fixes this, and also fixes some undefined behaviour on illumos. I've updated the PR.

2024-03-13 21:53 UTC, hadfl approved these changes

2024-03-14 05:48 UTC, citrus-it approved these changes

2024-03-14 05:48 UTC, merged