Bump vaultwarden to 1.30.5 and web vault to v2024.5.0
omniosorg/omnios-extra pull request #1464
Opened 2024-05-28 16:14 UTC by papertigers

Not yet built or tested but I noticed these are out of date with what's currently published to GitHub

2024-05-28 17:42 UTC, citrus-it requested changes
Thanks! Just the one comment.

2024-05-28 17:42 UTC, citrus-it commented on build/vaultwarden/build.sh
>  WEBVAULTSHA256=c9a63f9f71899ffbffac959f55fb651a5c3d31f6a58f36f728a1d4910dcbbb76
You're going to have to bump this checksum too.

2024-05-28 19:03 UTC, papertigers commented
Updated the checksum and built the package in my dev VM. Looks like some permissions changes but otherwise builds just fine:
```
***
*** Differences found between old and new packages
***
Do you wish to continue anyway? (y/n) y
===== User elected to continue after prompt. =====
-- Cleaning up
--- Removing temporary install directory /var/tmp/build_link/vaultwarden-1.30.5/ooce_application_vaultwarden_pkg
--- Cleaning up temporary manifest and transform files
Done.
Time: ooce/application/vaultwarden - 0h39m35s
```

2024-05-30 15:31 UTC, hadfl approved these changes

2024-05-31 09:11 UTC, oetiker approved these changes

2024-05-31 11:34 UTC, citrus-it approved these changes

2024-05-31 11:34 UTC, merged