Add hyperfine
omniosorg/omnios-extra pull request #618
Opened 2020-09-05 15:36 UTC by The-King-of-Toasters

Same developer as fd and bat, so I just used build.sh from fd.

2020-09-05 19:18 UTC, citrus-it requested changes
Thanks for the pull request, this looks like a useful utility to add.
I've put the source on our mirror now, can you please address these four small things.

Thanks!

2020-09-05 19:18 UTC, citrus-it commented on build/hyperfine/build.sh
> +download_source $PROG $PROG $VER
We'll put the source on our mirror with the name it comes off the github releases page, so can you adjust this to the following?
```suggestion
download_source $PROG v$VER
```

2020-09-05 19:18 UTC, citrus-it commented on build/hyperfine/build.sh
> +    logcmd cp target/release/$PROG $DESTDIR/$PREFIX/bin/fd || logerr "cp failed"
The binary name needs adjusting here.
```suggestion
    logcmd cp target/release/$PROG $DESTDIR/$PREFIX/bin/$PROG \
        || logerr "cp failed"
```

When I tried building this, I got:
```
ERROR pkglint.dupaction001.1      path opt/ooce/bin/fd is a duplicate delivered by pkg:/ooce/util/hyperfine@1.10.0,5.11-151034.0 pkg://extra.omnios/ooce/util/fd@7.3.0,5.11-151034.0:20200329T132943Z under all variant combinations
```

2020-09-05 19:18 UTC, citrus-it commented on build/hyperfine/build.sh
> +set_checksum none
Once it's on the mirror, there will be a checksum so please drop this line
```suggestion
```

2020-09-05 19:18 UTC, citrus-it commented on build/hyperfine/build.sh
> +SKIP_LICENCES=Various
The licence check works fine so you can drop this line too.
```suggestion
```

2020-09-05 23:59 UTC, The-King-of-Toasters commented
done

2020-09-06 13:48 UTC, hadfl approved these changes

2020-09-06 16:31 UTC, citrus-it approved these changes

2020-09-06 16:32 UTC, merged