sg3_utils: add
omniosorg/omnios-extra pull request #659
Opened 2020-10-01 11:38 UTC by cgrzemba

Please add utilities for devices that use SCSI command sets

2020-10-01 15:39 UTC, oetiker submitted a review, later dismissed

2020-10-01 16:06 UTC, citrus-it requested changes
Hi, thanks for submitting this pull request!

Please can you address the few comments I've posted inline?

Thanks,

Andy

2020-10-01 16:06 UTC, citrus-it commented on build/sg3-utils/patches/solaris.patch
> +
Can you add a line saying where you got this patch from please?
It looks like it originally came from solaris-userland, if so just leave a link back to the source.

2020-10-02 07:34 UTC, cgrzemba commented on build/sg3-utils/local.mog
> +# vim:ts=4:sw=4:et:fdm=marker
so we should also update README.md
```bash
diff --git a/README.md b/README.md
index 46a3ac3..70bae12 100644
--- a/README.md
+++ b/README.md
@@ -199,9 +199,6 @@ clean_up
 # Copyright YYYY your name/organisation
 
 license LICENCE license=CDDL
-
-# Vim hints
-# vim:ts=4:sw=4:et:fdm=marker
```

2020-10-02 14:53 UTC, citrus-it approved these changes

2020-10-02 15:03 UTC, citrus-it approved these changes

2020-10-02 15:13 UTC, hadfl approved these changes

2020-10-02 15:14 UTC, merged