add ncdu 1.15.1
omniosorg/omnios-extra pull request #880
Opened 2021-05-04 23:30 UTC by jclulow

2021-05-05 07:22 UTC, oetiker requested changes
an entryu in https://github.com/omniosorg/omnios-extra/blob/master/doc/packages.md is missing

2021-05-05 09:43 UTC, citrus-it commented on build/ncdu/build.sh
> +CFLAGS+=' -I/usr/include/ncurses '
Does this work with CPPFLAGS instead?

2021-05-05 09:47 UTC, citrus-it requested changes
Thanks Josh, that looks like a useful utility. Just a few nits, and please can you add the package to `doc/packages.md` so that our package update monitoring plugins can keep an eye on updates? 
Setting the URL there to https://dev.yorhel.nl/download should be enough for it to work. Please set the maintainer field to Oxide if they/you will be looking after it.

Can you also please add a line to `doc/baseline`?

2021-05-05 09:47 UTC, citrus-it commented on build/ncdu/build.sh
> +    'b02ddc4dbf1db139cc6fbbe2f54a282770380f0ca5c17089855eab52a9ea3fb0'
I've put the source on the omnios mirror now, so please drop these three lines

2021-05-05 09:47 UTC, citrus-it commented on build/ncdu/build.sh
> +CFLAGS+=' -I/usr/include/ncurses '
Does this work with CPPFLAGS instead?

2021-05-05 09:47 UTC, citrus-it commented on build/ncdu/local.mog
> +# vim:ts=4:sw=4:et:fdm=marker
We generally do not use the fold markers of the vim modeline in the .mog files, just a trailing blank line.

2021-05-05 10:13 UTC, citrus-it commented on build/ncdu/build.sh
> +strip_install
Since CTF conversion seems to work on all OmniOS releases, can you replace these two lines?

```suggestion
build -ctf
```

2021-06-01 23:48 UTC, jclulow commented
With my apologies for it taking so long, I think I've addressed all the feedback!  I've confirmed that the package still builds.  Let me know if you need anything else.

2021-06-02 16:45 UTC, hadfl approved these changes

2021-06-02 16:47 UTC, merged